CREATE DATABASE IF NOT EXISTS "PANDA_PROJECT";

DROP TABLE IF EXISTS PP_USERS CASCADE;

CREATE TABLE "PP_USERS" (
  "user_id" NUMBER,
  "username" VARCHAR,
  "role_id" NUMBER,
  "project_id" NUMBER NULL,
  PRIMARY KEY ("user_id")
);

ALTER TABLE PP_USERS ADD CONSTRAINT UNIQUE (username);

CREATE INDEX "USER_NAME_IDX" ON  "PP_USERS" ("username");

DROP TABLE IF EXISTS PP_ROLES CASCADE;

CREATE TABLE "PP_ROLES" (
  "role_id" NUMBER,
  "name" VARCHAR,
  PRIMARY KEY ("role_id")
);

ALTER TABLE PP_USERS ADD CONSTRAINT FOREIGN KEY (role_id) REFERENCES PP_ROLES(role_id);

DROP TABLE IF EXISTS PP_PROJECTS CASCADE;

CREATE TABLE "PP_PROJECTS" (
  "project_id" NUMBER,
  "manager" NUMBER,
  "project_key" VARCHAR,
  "description" VARCHAR NULL,
  PRIMARY KEY ("project_id")
);

ALTER TABLE PP_PROJECTS ADD CONSTRAINT UNIQUE (project_key);
ALTER TABLE PP_PROJECTS ADD CONSTRAINT FOREIGN KEY (manager) REFERENCES PP_USERS(user_id);
ALTER TABLE PP_USERS ADD CONSTRAINT FOREIGN KEY (project_id) REFERENCES PP_PROJECTS(project_id);

DROP TABLE IF EXISTS PP_TICKETS CASCADE;

CREATE TABLE "PP_TICKETS" (
  "ticket_key" VARCHAR,
  "project_id" NUMBER,
  "assignee" NUMBER,
  "name" VARCHAR,
  "ticket_status_id" NUMBER,
  "due_date" DATE NULL,
  "ticket_type_id" NUMBER,
  "description" VARCHAR NULL
);

ALTER TABLE PP_TICKETS ADD CONSTRAINT UNIQUE (ticket_key);
ALTER TABLE PP_TICKETS ADD CONSTRAINT FOREIGN KEY (project_id) REFERENCES PP_PROJECTS(project_id);
ALTER TABLE PP_TICKETS ADD CONSTRAINT FOREIGN KEY (assignee) REFERENCES PP_USERS(user_id);

CREATE INDEX "TICKET_KEY_IDX" ON  "PP_TICKETS" ("ticket_key");

CREATE INDEX "TICKET_PROJECT_IDX" ON  "PP_TICKETS" ("project_id");

CREATE INDEX "TICKET_USER_IDX" ON  "PP_TICKETS" ("assignee");

CREATE INDEX "TICKET_STATUS_IDX" ON  "PP_TICKETS" ("ticket_status_id");

CREATE INDEX "TICKET_DUE_IDX" ON  "PP_TICKETS" ("due_date");

CREATE INDEX "TICKET_TYPE_IDX" ON  "PP_TICKETS" ("ticket_type_id");

CREATE TABLE "PP_TICKET_STATUSES" (
  "ticket_status_id" NUMBER,
  "name" VARCHAR,
  PRIMARY KEY ("ticket_status_id")
);

ALTER TABLE PP_TICKETS ADD CONSTRAINT FOREIGN KEY (ticket_status_id) REFERENCES PP_TICKET_STATUSES(ticket_status_id);

DROP TABLE IF EXISTS PP_TICKET_TYPES CASCADE;

CREATE TABLE "PP_TICKET_TYPES" (
  "ticket_type_id" NUMBER,
  "name" VARCHAR,
  PRIMARY KEY ("ticket_type_id")
);

ALTER TABLE PP_TICKET_TYPES ADD CONSTRAINT FOREIGN KEY (ticket_type_id) REFERENCES PP_TICKET_TYPES(ticket_type_id);
